### ISSUE TITLE
bug: error, not loading in Ubunbtu 20.04

### ISSUE THREAD

**Issue by scalefree** [Neopallium/lludp_dissector#2]
When I try running in wireshark 3.2.3 under Ubuntu 20.04 I get the following error & the dissector does not appear to work

> bad argument #3 to 'bytes' (DIsplay must be either base.NONE, base.DOT, base.DASH, base.COLON or base.SPACE)

**Comment by Neopallium** [comment]
I am also using wireshark 3.2.3 on Ubuntu 20.04 without any problems.  Do you only get that error on a few packets?  Can you send me the packet that causes that error?

**Comment by scalefree** [comment]
Don't have a chance to load packets, I get that on boot even before I turn capture on.

**Comment by scalefree** [comment]
Took some playing around but I discovered the proper location for plugins, 
 [user]/.local/lib/wireshark/plugins. However I get some new errors.  On boot I get this:

> Lua: Error during loading:
[user]/.local/lib/wireshark/plugins/lludp/dissector.lua:51: bad argument #2 to 'Proto' (Proto_new: there cannot be two protocols with the same description)
stack traceback:
	[C]: in function 'Proto'
	[user]/.local/lib/wireshark/plugins/lludp/dissector.lua:51: in main chunk

Line 51 reads

> local lludp_proto = Proto("lludp","LLUDP","LindenLabs UDP Protocol")

When I turn on capture I get this one:

> Lua: Error During execution of Initialization:
 LLUDP: Failed parse file into tokens: message_template.msg
[user]/.local/lib/wireshark/plugins/lludp/lexer.lua:72: cannot open file 'message_template.msg' (No such file or directory)

Turns out that filename is also defined in dissector.lua, lines 54 & 55:

> lludp_proto.prefs["template_file"] =
	Pref.string("Message template file", "message_template.msg", "Message template file")

This is where I am.  What am I getting wrong?

**Comment by scalefree** [comment]
On the upside the dissector does seem to be at least partially working, I can see packets tagged LLUDP.  Not sure yet if it's fully functional but it's progress.

**Comment by Neopallium** [comment]
It looks like you are loading the dissector twice.  lludp_dissector wasn't designed for wireshark's plugin loading design, I will look into making it easier to use like that.  But for now you can use the below setup that I have been using.  Also the dissector failed to load the "message_template.msg" file, it needs the path to that file.  I normally put a copy of that file into my "$HOME/.wireshark/" folder.

Even without the "message_template.msg" the dissector should be able to decode the LLUDP packet headers, but will not be able to show any details of each message.

My setup has been this:
1. Make folder for lua files "$HOME/lua"
2. Set LUA_PATH & LUA_CPATH in "$HOME/.bash_profile":
```bash
export LUA_PATH="$HOME/lua?.lua;;"
## LUA_CPATH is not required for this dissector.
export LUA_CPATH="$HOME/lua?.so;;"
```
3. Copy the files from lludp/*.lua from this repository to "$HOME/lua/lludp/"
4. Copy the init.lua file to "$HOME/.wireshark/init.lua"
5. Set the path to the message template file in Wireshark -> Preferences -> Protocol -> LLUDP.

Steps 1-3 could be replaced with installing the "lludp" folder into "/usr/local/share/lua/5.3/lludp" (replace 5.3 with your lua version).

You will need to get a copy of the "message_template.msg" file from one of the Second Life viewers, should be in the "app_settings" folder of the installed viewer.

Your first error might have been from not having the "message_template.msg" file loaded.  I will try doing some testing to see if that is the case.

**Comment by scalefree** [comment]
Thanks so much.  This is exactly what I've been looking for.  I'll try it out tomorrow & let you know how it goes.

**Comment by scalefree** [comment]
Where do I put .luacheckrc?

**Comment by scalefree** [comment]
I had to play around a bit with which dirs to put things in for it to work for me but in the end I got it so thanks so much.  Closing ticket.
